import express from 'express';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),app=express(),PORT=Number(process.env.PORT||3000),DATA_DIR=path.join(__dirname,'data'),MESSAGE_FILE=path.join(DATA_DIR,'contact-messages.jsonl');app.use(express.json({limit:'256kb'}));app.use(express.urlencoded({extended:false}));
async function persistMessage(x:unknown){await fs.mkdir(DATA_DIR,{recursive:true});await fs.appendFile(MESSAGE_FILE,`${JSON.stringify(x)}\n`,'utf8')}async function readMessages():Promise<any[]>{try{const r=await fs.readFile(MESSAGE_FILE,'utf8');return r.split('\n').filter(Boolean).map(x=>JSON.parse(x)).reverse()}catch(e:any){if(e?.code==='ENOENT')return[];throw e}}async function writeMessages(m:any[]){await fs.mkdir(DATA_DIR,{recursive:true});const c=[...m].reverse();await fs.writeFile(MESSAGE_FILE,c.map(x=>JSON.stringify(x)).join('\n')+(c.length?'\n':''),'utf8')}
function requireAdmin(req:express.Request,res:express.Response,next:express.NextFunction){const u=process.env.ADMIN_USERNAME,p=process.env.ADMIN_PASSWORD;if(!u||!p)return res.status(503).send('Admin console is not configured.');const h=req.get('authorization')||'';if(h.startsWith('Basic ')){try{const[a,b]=Buffer.from(h.slice(6),'base64').toString('utf8').split(':');if(a===u&&b===p)return next()}catch{}}res.set('WWW-Authenticate','Basic realm="Quinnverse Studio"');return res.status(401).send('Authentication required.')}
const esc=(v:unknown)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
app.post('/api/contact-messages',async(req,res)=>{try{const b=req.body??{},source=String(b.source||'').trim(),email=String(b.email||'').trim(),message=String(b.message||b.description||'').trim();if(!source||!email||!message)return res.status(400).json({ok:false,error:'missing_required_fields'});const record={id:`msg_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,createdAt:new Date().toISOString(),source,status:'unread',name:String(b.name||'').trim(),email,topic:String(b.topic||b.direction||'').trim(),message,userAgent:String(req.get('user-agent')||''),ip:req.ip};await persistMessage(record);return res.json({ok:true,id:record.id})}catch(e){console.error('contact message persistence failed',e);return res.status(500).json({ok:false,error:'persist_failed'})}});
app.get('/admin',requireAdmin,(_req,res)=>res.redirect(302,'/admin/messages'));
app.get('/admin/messages',requireAdmin,async(_req,res)=>{const ms=await readMessages(),rows=ms.map(m=>`<article class="card ${esc(m.status)}"><div class="meta"><strong>${esc(m.name||'未留称呼')}</strong><span>${esc(m.email)}</span><span>${esc(m.createdAt)}</span><span>${esc(m.source)}</span></div><h3>${esc(m.topic||'无主题')}</h3><p>${esc(m.message)}</p><form method="post" action="/admin/messages/${encodeURIComponent(m.id)}/status"><select name="status">${['unread','read','replied','archived'].map(s=>`<option value="${s}" ${m.status===s?'selected':''}>${({unread:'未读',read:'已读',replied:'已回复',archived:'归档'} as any)[s]}</option>`).join('')}</select><button>更新状态</button></form></article>`).join('');res.set('Cache-Control','no-store');res.type('html').send(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Quinnverse Studio</title><style>body{font-family:system-ui,sans-serif;background:#f8fafc;color:#0f172a;margin:0}.wrap{max-width:1000px;margin:auto;padding:40px 20px}h1{font-size:28px}.hint{color:#64748b}.card{background:white;border:1px solid #e2e8f0;border-radius:18px;padding:20px;margin:14px 0}.card.unread{border-left:4px solid #2563eb}.meta{display:flex;gap:12px;flex-wrap:wrap;font-size:12px;color:#64748b}.card p{white-space:pre-wrap;line-height:1.7}form{display:flex;gap:8px;margin-top:16px}select,button{padding:8px 12px;border:1px solid #cbd5e1;border-radius:10px;background:white}button{background:#0f172a;color:white}</style></head><body><main class="wrap"><h1>Quinnverse Studio · 消息</h1><p class="hint">${ms.length} 条消息。后台不出现在公开导航中，并由服务端认证保护。</p>${rows||'<p>暂无消息。</p>'}</main></body></html>`)});
app.post('/admin/messages/:id/status',requireAdmin,async(req,res)=>{const allowed=new Set(['unread','read','replied','archived']),status=String(req.body.status||'');if(!allowed.has(status))return res.status(400).send('Invalid status');const ms=await readMessages(),t=ms.find(m=>m.id===req.params.id);if(!t)return res.status(404).send('Message not found');t.status=status;t.updatedAt=new Date().toISOString();await writeMessages(ms);return res.redirect(303,'/admin/messages')});
const distDir=path.join(__dirname,'dist');app.use(express.static(distDir));app.get('*',(_req,res)=>res.sendFile(path.join(distDir,'index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`Quinnverse server listening on :${PORT}`));
