import React,{useState} from 'react';
import {Link} from '../utils/router';
import {PRODUCTS,PICKS,LAB_EXPERIMENTS,JOURNAL_ARTICLES,RESOURCES} from '../data/database';

type Props={route:string};
const Shell:React.FC<{eyebrow:string;title:string;intro:string;children?:React.ReactNode}>=({eyebrow,title,intro,children})=><div className="py-16 sm:py-24 bg-[#F8FAFC]"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 space-y-10"><header className="max-w-3xl space-y-3"><div className="inline-block text-xs font-bold text-blue-600 bg-blue-50 border border-blue-200 px-3.5 py-1 rounded-full">{eyebrow}</div><h1 className="font-display text-4xl sm:text-6xl font-black tracking-tight">{title}</h1><p className="text-sm sm:text-base text-slate-600 leading-relaxed">{intro}</p></header>{children}</div></div>;
const Cards:React.FC<{items:{title:string;body:string;href?:string}[]}>=({items})=><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{items.map((x,i)=><div key={i} className="rounded-3xl border border-slate-200 bg-white p-7 space-y-3"><h2 className="text-xl font-bold">{x.title}</h2><p className="text-sm text-slate-600 leading-relaxed">{x.body}</p>{x.href&&<Link to={x.href} className="inline-block text-xs font-bold text-blue-600">Read more →</Link>}</div>)}</div>;
const productCopy:Record<string,[string,string,string[]]>= {'job-application-copilot':['Job Application Copilot / Job OS','A deterministic workspace for capturing job listings, tracking applications and reducing repetitive ATS form filling.',['Capture structured job information from supported recruiting pages.','Track Saved → Applied → Interviewing → Offered in one workspace.','Use deterministic autofill based only on user-confirmed information.','Keep the final submission decision with the applicant.']],tingmo:['TingMo','Turn study notes into an audio-first review workflow with sentence loops and spoken recall.',['Loop difficult sentences instead of replaying an entire recording.','Practice active spoken recall after listening.','Keep learning progress lightweight and local.']], 'weread-dashboard':['WeRead Dashboard','A personal reading dashboard that turns scattered reading activity, highlights and annotations into a longer-term view.',['Aggregate reading time and activity.','Bring highlights and annotations into one place.','Review reading patterns over longer periods.']], 'cloze-recitation':['Cloze Recitation','An active-recall trainer that converts source text into fill-in-the-blank practice.',['Practice retrieval rather than passive rereading.','Use keyboard-first review for fast repetition.','Increase masking density as recall improves.']]};
const pickCopy:Record<string,[string,string,string,string]>= {cursor:['Cursor','An AI-first code editor used for project-level navigation, refactoring and completion.','Strong for fast cross-file work and reducing repetitive implementation effort.','Large repositories and long agentic sessions still require review; generated edits should not be accepted blindly.'],n8n:['n8n','A self-hostable workflow automation platform for APIs, webhooks and data pipelines.','Strong when data control and custom integrations matter.','Self-hosting adds deployment, logging and operational work.'],obsidian:['Obsidian','A local-first Markdown knowledge base with backlinks and a broad plugin ecosystem.','Strong for durable personal knowledge assets and workflows built around plain files.','It takes setup to become a polished personal system, and official sync is a separate service.'],dify:['Dify','A visual platform for prototyping LLM applications, knowledge retrieval and agent workflows.','Useful for quickly testing an AI product flow before investing in custom infrastructure.','Complex branching can make visual flows difficult to maintain.'],comfyui:['ComfyUI','A node-based interface for controllable image-generation workflows.','Useful when reproducibility and fine-grained generation control matter.','The learning curve and custom-node dependency management can be significant.'],gemini:['Gemini','Google’s multimodal model ecosystem, tested for long-context analysis and multimodal tasks.','Useful when very large context windows and multimodal inputs are central to the task.','Availability, model behavior and product limits can change, so current requirements should be verified before committing a workflow.']};
function ContactForm({source}:{source:string}){const[status,setStatus]=useState('');const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setStatus('Sending…');const f=new FormData(e.currentTarget);const r=await fetch('/api/contact-messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source,name:f.get('name'),email:f.get('email'),topic:f.get('topic'),message:f.get('message')})});setStatus(r.ok?'Message saved. Thank you.':'Could not save the message. Please try again.');};return <form onSubmit={submit} className="max-w-2xl rounded-3xl border bg-white p-7 space-y-4"><input name="name" placeholder="Name" className="w-full rounded-xl border p-3"/><input name="email" type="email" required placeholder="Email" className="w-full rounded-xl border p-3"/><input name="topic" placeholder="Subject / collaboration type" className="w-full rounded-xl border p-3"/><textarea name="message" required placeholder="Message" rows={6} className="w-full rounded-xl border p-3"/><button className="px-6 py-3 rounded-full bg-slate-900 text-white text-sm font-bold">Send message</button><span className="ml-3 text-xs text-slate-500">{status}</span></form>}
export const EnglishPublicPage:React.FC<Props>=({route})=>{
 const parts=route.split('/').filter(Boolean),root='/'+(parts[0]||''),slug=parts[1];
 if(root==='/products'&&slug){const c=productCopy[slug]||[slug.replaceAll('-',' '),'An independent Quinnverse product built around a concrete problem.',['Designed around a specific workflow.','Built and tested as a working implementation.','Iterated from real usage rather than a feature checklist.']] as [string,string,string[]];return <Shell eyebrow="BUILT BY QUINNVERSE" title={c[0]} intro={c[1]}><Cards items={c[2].map(x=>({title:'Capability',body:x}))}/><Link to="/en/products" className="text-sm font-bold">← Back to Products</Link></Shell>}
 if(root==='/products')return <Shell eyebrow="INDEPENDENT PRODUCTS" title="Products" intro="Software and focused tools built from problems encountered in real work and daily life."><Cards items={PRODUCTS.map(p=>{const c=productCopy[p.slug];return {title:c?.[0]||p.name,body:c?.[1]||'A Quinnverse-built tool.',href:`/en/products/${p.slug}`}})}/></Shell>;
 if(root==='/picks'&&slug){const c=pickCopy[slug]||[slug,'A tool tested by Quinnverse.','The useful parts are recorded from hands-on use.','Limitations are kept visible rather than hidden behind a recommendation.'];return <Shell eyebrow="TESTED, NOT JUST LISTED" title={c[0]} intro={c[1]}><Cards items={[{title:'What we found',body:c[2]},{title:'Where it falls short',body:c[3]}]}/><Link to="/en/picks" className="text-sm font-bold">← Back to Tested</Link></Shell>}
 if(root==='/picks')return <Shell eyebrow="TESTED TOOL LIBRARY" title="Tested" intro="Tools Quinnverse has actually used or tested, with evidence levels and limitations kept visible."><Cards items={PICKS.map(p=>({title:p.name,body:`Evidence: ${p.evidenceLevel}. Last tested: ${p.lastTested}.`,href:`/en/picks/${p.slug}`}))}/></Shell>;
 if(root==='/finder')return <Shell eyebrow="TOOL FINDER" title="Find a tool for the problem you actually have." intro="Start from the task, constraints, access requirements and budget instead of browsing an endless directory."><Cards items={[{title:'1. Define the job',body:'What are you trying to accomplish: coding, automation, knowledge work, agent prototyping or visual generation?'},{title:'2. Set constraints',body:'Consider technical comfort, network availability, privacy requirements and budget.'},{title:'3. Compare evidence',body:'Use the Tested library to compare a short list, including the trade-offs.'}]}/><Link to="/en/picks" className="inline-block px-6 py-3 rounded-full bg-slate-900 text-white text-sm font-bold">Browse Tested →</Link></Shell>;
 if(root==='/lab'&&slug)return <Shell eyebrow="QUINNVERSE LAB" title={slug.replaceAll('-',' ')} intro="A Quinnverse Lab entry documenting what was built, what was tested and what changed after the experiment."><Cards items={[{title:'Why this exists',body:'The experiment starts from a concrete product, workflow or engineering question.'},{title:'What gets recorded',body:'Implementation choices, observations, failures and reusable conclusions are kept together.'}]}/><Link to="/en/lab" className="text-sm font-bold">← Back to Lab</Link></Shell>;
 if(root==='/lab')return <Shell eyebrow="BUILD · EXPERIMENT · LEARN" title="Lab" intro="One home for build logs, product experiments, methods and field notes."><Cards items={[...LAB_EXPERIMENTS.map(x=>({title:'Product Experiment',body:`Experiment: ${x.slug}`,href:`/en/lab/${x.slug}`})),...JOURNAL_ARTICLES.map(x=>({title:'Build Log / Field Note',body:`Note: ${x.slug}`,href:`/en/journal/${x.slug}`})),...RESOURCES.map(x=>({title:'Method & Guide',body:`Guide: ${x.slug}`,href:`/en/resources/${x.slug}`}))]}/></Shell>;
 if(root==='/journal'&&slug)return <Shell eyebrow="FIELD NOTE" title={slug.replaceAll('-',' ')} intro="A field note from Quinnverse: context, observations, decisions and lessons from actual work."/>;
 if(root==='/journal')return <Shell eyebrow="FIELD NOTES" title="Build Logs & Notes" intro="Older direct links remain available, while new discovery happens through Lab."><Cards items={JOURNAL_ARTICLES.map(x=>({title:x.slug.replaceAll('-',' '),body:'Build log or field note.',href:`/en/journal/${x.slug}`}))}/></Shell>;
 if(root==='/resources'&&slug)return <Shell eyebrow="METHOD & GUIDE" title={slug.replaceAll('-',' ')} intro="A reusable Quinnverse guide distilled from hands-on work."/>;
 if(root==='/resources')return <Shell eyebrow="METHODS & GUIDES" title="Resources" intro="Older direct links remain available, while methods and guides are now discoverable through Lab."><Cards items={RESOURCES.map(x=>({title:x.slug.replaceAll('-',' '),body:'Reusable guide or method.',href:`/en/resources/${x.slug}`}))}/></Shell>;
 if(root==='/about')return <Shell eyebrow="ABOUT" title="Quinnverse is an independent product studio." intro="I turn recurring problems from work and daily life into products, small tools, experiments and reusable methods. The site is also a public record of what was tested, what worked and what did not."><Cards items={[{title:'Build',body:'Create focused software from concrete problems.'},{title:'Test',body:'Use tools in real scenarios before recommending them.'},{title:'Document',body:'Keep experiments, methods and lessons accessible in Lab.'}]}/></Shell>;
 if(root==='/contact')return <Shell eyebrow="CONTACT & FEEDBACK" title="Contact Quinnverse" intro="For product feedback, technical questions or general contact. Messages are stored in the private Quinnverse Studio inbox."><ContactForm source="contact"/><p className="text-sm text-slate-600">Direct email: zhangqiyun2000@163.com</p></Shell>;
 if(root==='/work-with-us')return <Shell eyebrow="COLLABORATION" title="Work with Quinnverse" intro="For product or technical collaboration, tool testing, inclusion requests and content or channel partnerships."><ContactForm source="work-with-us"/></Shell>;
 if(root==='/disclosure')return <Shell eyebrow="TRANSPARENCY" title="Commercial transparency" intro="Testing conclusions and evidence levels are kept separate from commercial relationships. Affiliate or sponsored relationships, when present, should be disclosed rather than silently influencing recommendations."/>;
 return <Shell eyebrow="404" title="Page not found" intro="The page may have moved or does not exist."><Link to="/en" className="font-bold text-blue-600">Back to Quinnverse →</Link></Shell>;
};
