import React from 'react';
import { ArrowRight, ExternalLink, Check } from 'lucide-react';
import { Link } from '../utils/router';
import { PRODUCTS } from '../data/database';
import { EN } from '../i18n/en';
import { localizePath, type Locale } from '../i18n/locale';

export const ProductsPage: React.FC<{locale?:Locale}> = ({locale='zh'}) => {
  const en=locale==='en', t=EN.products;
  const featured=PRODUCTS.find(p=>p.family==='GLOBAL_PRODUCT')||PRODUCTS[0];
  const smallTools=PRODUCTS.filter(p=>p.family==='SMALL_TOOL');
  const toolImages:Record<string,string>={tingmo:'/src/assets/images/card_nature_waterfall_1790959793831.jpg','weread-dashboard':'/src/assets/images/card_sunset_architecture_1790959809823.jpg','cloze-recitation':'/src/assets/images/card_tropical_beach_1790959840986.jpg'};
  return <div className="py-16 sm:py-24 bg-[#F8FAFC] text-left"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 space-y-16">
    <div className="max-w-3xl space-y-3"><div className="inline-block text-xs font-bold text-blue-600 bg-blue-50 border border-blue-200 px-3.5 py-1 rounded-full">{en?t.eyebrow:'自研软件矩阵'}</div><h1 className="font-display text-4xl sm:text-6xl font-black text-slate-950 tracking-tight leading-tight">{en?t.title:'因为缺少好用的工具，所以自己做。'}</h1><p className="text-sm sm:text-base text-slate-600 leading-relaxed">{en?t.intro:'这里是 Quinnverse 亲自设计、编码与维护的软件产品。有些卡点需要完整系统，有些问题一个小工具就足够。'}</p></div>
    <section className="space-y-6"><div className="text-xs font-mono text-slate-900 font-bold uppercase tracking-wider">{en?t.featured:'01 / 当前主线旗舰产品'}</div><div className="rounded-3xl border border-slate-200 bg-white overflow-hidden shadow-xl"><div className="grid lg:grid-cols-12"><div className="lg:col-span-7 p-7 sm:p-12 space-y-8"><div><h2 className="font-display text-3xl sm:text-4xl font-extrabold">{featured.name}</h2><p className="mt-3 text-xl font-bold text-slate-800">{featured.tagline}</p><p className="mt-3 text-sm text-slate-600 leading-relaxed">{featured.problemSolved}</p></div><div className="grid md:grid-cols-2 gap-6 pt-6 border-t"><div><div className="text-xs font-bold text-slate-400 uppercase">{en?t.capabilities:'核心能力矩阵'}</div><ul className="mt-3 space-y-2 text-sm">{featured.features.map((x,i)=><li key={i}>· {x}</li>)}</ul></div><div><div className="text-xs font-bold text-slate-400 uppercase">{en?t.principles:'确定性工程原则'}</div><ul className="mt-3 space-y-2 text-sm">{featured.principles.map((x,i)=><li key={i} className="flex gap-2"><Check className="w-4 h-4 text-emerald-600 shrink-0"/>{x}</li>)}</ul></div></div><Link to={localizePath(`/products/${featured.slug}`,locale)} className="inline-flex items-center gap-2 px-6 py-3 text-xs font-bold text-white bg-slate-900 rounded-full">{en?t.details:'查看详细处理链路与内测申请'} <ArrowRight className="w-3.5 h-3.5"/></Link></div><div className="lg:col-span-5 min-h-[320px]"><img src="/src/assets/images/hero_studio_showcase_1790959723676.jpg" alt={featured.name} className="w-full h-full object-cover"/></div></div></div></section>
    <section className="space-y-6"><div><div className="text-xs font-bold text-blue-600 uppercase">{en?t.small:'02 / 轻量自用小工具矩阵'}</div><h2 className="mt-2 font-display text-2xl sm:text-3xl font-extrabold">{en?t.smallTitle:'有些问题值得成为完整产品。有些问题，一个小工具就够了。'}</h2></div><div className="grid md:grid-cols-3 gap-6">{smallTools.map(tool=><div key={tool.id} className="rounded-3xl border border-slate-200 bg-white overflow-hidden"><img src={toolImages[tool.slug]||toolImages.tingmo} alt={tool.name} className="h-44 w-full object-cover"/><div className="p-6 space-y-3"><h3 className="text-xl font-bold">{tool.name}</h3><p className="text-xs font-semibold">{tool.tagline}</p><p className="text-xs text-slate-600 leading-relaxed">{tool.problemSolved}</p></div><div className="p-6 pt-4 border-t bg-slate-50/50 flex justify-end"><a href={tool.externalUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full bg-slate-900 text-white text-xs font-bold">{en?t.open:'打开工具'} <ExternalLink className="w-3.5 h-3.5"/></a></div></div>)}</div></section>
  </div></div>;
};
